version: "3.8"

services:
  app:
    image: harystyles/privexbot-frontend@sha256:c22827b655639479d0a81f5c5e627d901161c3b5d973d7839f8f36a581c363a7
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - API_BASE_URL=https://api.privexbot.com/api/v1
      - WIDGET_CDN_URL=https://cdn.privexbot.com
      - ENVIRONMENT=production
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`silver-hedgehog.vm.scrtlabs.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.services.app.loadbalancer.server.port=80

  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.options=default@file
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/secure/cert:/certs:ro
    networks:
      - traefik
    configs:
      - source: tls_config
        target: /etc/traefik/dynamic/tls.yml

networks:
  traefik:
    driver: bridge

configs:
  tls_config:
    content: |-
      tls:
        certificates:
          - certFile: /certs/secret_vm_fullchain.pem
            keyFile: /certs/secret_vm_private.pem
        stores:
          default:
            defaultCertificate:
              certFile: /certs/secret_vm_fullchain.pem
              keyFile: /certs/secret_vm_private.pem
